version: '3.4'

services:
    app:
        build: . # locate dockerfile
        volumes:
        - .:/opt/app # shared folder
        - yarn-cache:/opt/.yarn-cache # cache
        ports:
        - '3000:3000' # port mirror
        environment:
            PORT: '3000'

    dynamodb:
        image: deangiberson/aws-dynamodb-local

volumes:
    yarn-cache:
